In [2]:
#라이브러리 불러오기
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#데이터 불러오기
customer_df = pd.read_csv('/Users/chrishegangkim/Desktop/2025 Spring/Python/Data Analysis Project/data/customer_data.csv', sep = '\t') #탭으로 구분되어 있는 데이터 불러오기

In [4]:
#데이터 탐색하기
customer_df.shape #데이터 크기 (row, column)

(2240, 23)

In [5]:
pd.set_option('display.max_columns', None) #화면에 표시되는 컬럼 개수의 제한을 해제하기
customer_df.head() #데이터의 첫 다섯 줄을 확인하기

,ID,signup_ym,birth_year,annual_income,marital_status,children,recency,amount_alcohol,amount_fruit,amount_meat,amount_fish,amount_snack,amount_general,num_purchase_web,num_purchase_store,num_purchase_discount,promotion_1,promotion_2,promotion_3,promotion_4,promotion_5,promotion_6,revenue
0,5524,2020-12,1965,75579400.0,미혼,0,58,825500,114400,709800,223600,114400,114400,8,4,3,0,0,0,0,0,1,11
1,2174,2022-06,1962,60247200.0,미혼,2,38,14300,1300,7800,2600,1300,7800,1,2,2,0,0,0,0,0,0,11
2,4141,2021-11,1973,93096900.0,배우자 있음,0,26,553800,63700,165100,144300,27300,54600,8,10,1,0,0,0,0,0,0,11
3,6182,2022-05,1992,34639800.0,배우자 있음,1,26,14300,5200,26000,13000,3900,6500,2,4,2,0,0,0,0,0,0,11
4,5324,2022-04,1989,75780900.0,배우자 있음,1,94,224900,55900,153400,59800,35100,19500,5,6,5,0,0,0,0,0,0,11

In [6]:
customer_df.info() #각 컬럼의 데이터 타입과 non-null 데이터 개수를 확인하기

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     2240 non-null   int64
 1   signup_ym              2240 non-null   object
 2   birth_year             2240 non-null   int64
 3   annual_income          2216 non-null   float64
 4   marital_status         2240 non-null   object
 5   children               2240 non-null   int64
 6   recency                2240 non-null   int64
 7   amount_alcohol         2240 non-null   int64
 8   amount_fruit           2240 non-null   int64
 9   amount_meat            2240 non-null   int64
 10  amount_fish            2240 non-null   int64
 11  amount_snack           2240 non-null   int64
 12  amount_general         2240 non-null   int64
 13  num_purchase_web       2240 non-null   int64
 14  num_purchase_store     2240 non-null   int64
 15  num_purchase_discount  2240 non-null   int64
 16  promotion_1            2240 non-null   int64
 17  promotion_2            2240 non-null   int64
 18  promotion_3            2240 non-null   int64
 19  promotion_4            2240 non-null   int64
 20  promotion_5            2240 non-null   int64
 21  promotion_6            2240 non-null   int64
 22  revenue                2240 non-null   int64
dtypes: float64(1), int64(20), object(2)
memory usage: 402.6+ KB

In [7]:
customer_df.describe(include = 'all') #통계 정보 확인하기

,ID,signup_ym,birth_year,annual_income,marital_status,children,recency,amount_alcohol,amount_fruit,amount_meat,amount_fish,amount_snack,amount_general,num_purchase_web,num_purchase_store,num_purchase_discount,promotion_1,promotion_2,promotion_3,promotion_4,promotion_5,promotion_6,revenue
count,2240.000000,2240,2240.000000,2.216000e+03,2240,2240.000000,2240.000000,2.240000e+03,2240.000000,2.240000e+03,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0
unique,NaN,24,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,2021-12,NaN,NaN,배우자 있음,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,111,NaN,NaN,1444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,5592.159821,NaN,1976.805804,6.792143e+07,NaN,0.950446,49.109375,3.951164e+05,34192.901786,2.170350e+05,48783.080357,35181.830357,57228.437500,4.084821,5.790179,2.325000,0.064286,0.013393,0.072768,0.074554,0.072768,0.149107,11.0
std,3246.662198,NaN,11.984069,3.272500e+07,NaN,0.751803,28.962453,4.375766e+05,51705.463894,2.934300e+05,71017.673224,53664.648034,67817.670589,2.778714,3.250958,1.932238,0.245316,0.114976,0.259813,0.262728,0.259813,0.356274,0.0
min,0.000000,NaN,1901.000000,2.249000e+06,NaN,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.0
25%,2828.250000,NaN,1967.000000,4.589390e+07,NaN,0.000000,24.000000,3.087500e+04,1300.000000,2.080000e+04,3900.000000,1300.000000,11700.000000,2.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.0
50%,5458.500000,NaN,1978.000000,6.679595e+07,NaN,1.000000,49.000000,2.255500e+05,10400.000000,8.710000e+04,15600.000000,10400.000000,31200.000000,4.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.0
75%,8427.750000,NaN,1985.000000,8.907860e+07,NaN,1.000000,74.000000,6.555250e+05,42900.000000,3.016000e+05,65000.000000,42900.000000,72800.000000,6.000000,8.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.0
max,11191.000000,NaN,2004.000000,8.666658e+08,NaN,3.000000,99.000000,1.940900e+06,258700.000000,2.242500e+06,336700.000000,341900.000000,470600.000000,27.000000,13.000000,15.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.0

In [8]:
columns_object_dtype = customer_df.columns[customer_df.dtypes == 'object'] #데이터 타입이 object인 컬럼들을 뽑아내기
columns_object_dtype

Index(['signup_ym', 'marital_status'], dtype='object')

In [9]:
for col in columns_object_dtype: #데이터 타입이 object인 컬럼을 순회하기
    unique_values = sorted(customer_df[col].unique()) #unique한 값을 구하고 정렬하기
    print(f'{col}: {len(unique_values)}개')
    print(unique_values, '\n')

signup_ym: 24개
['2020-10', '2020-11', '2020-12', '2021-01', '2021-02', '2021-03', '2021-04', '2021-05', '2021-06', '2021-07', '2021-08', '2021-09', '2021-10', '2021-11', '2021-12', '2022-01', '2022-02', '2022-03', '2022-04', '2022-05', '2022-06', '2022-07', '2022-08', '2022-09']

marital_status: 4개
['미혼', '배우자 있음', '사별', '이혼']

In [10]:
#annual_income 컬럼 결측값 처리하기
customer_df.isna().sum() #결측값이 있는지 다시 한번 확인하기

ID                        0
signup_ym                 0
birth_year                0
annual_income            24
marital_status            0
children                  0
recency                   0
amount_alcohol            0
amount_fruit              0
amount_meat               0
amount_fish               0
amount_snack              0
amount_general            0
num_purchase_web          0
num_purchase_store        0
num_purchase_discount     0
promotion_1               0
promotion_2               0
promotion_3               0
promotion_4               0
promotion_5               0
promotion_6               0
revenue                   0
dtype: int64

In [11]:
customer_df = customer_df.dropna() #전체 데이터의 1% 수준인 24개 데이터 제거하기
customer_df.isna().sum()

ID                       0
signup_ym                0
birth_year               0
annual_income            0
marital_status           0
children                 0
recency                  0
amount_alcohol           0
amount_fruit             0
amount_meat              0
amount_fish              0
amount_snack             0
amount_general           0
num_purchase_web         0
num_purchase_store       0
num_purchase_discount    0
promotion_1              0
promotion_2              0
promotion_3              0
promotion_4              0
promotion_5              0
promotion_6              0
revenue                  0
dtype: int64

In [12]:
#출생 연도를 나이로 바꾸기
customer_df['birth_year'] = 2023 - customer_df['birth_year']

In [13]:
customer_df = customer_df.rename(columns = {'birth_year' : 'age'}) #컬럼 이름을 age로 바꾸기
customer_df.head()

,ID,signup_ym,age,annual_income,marital_status,children,recency,amount_alcohol,amount_fruit,amount_meat,amount_fish,amount_snack,amount_general,num_purchase_web,num_purchase_store,num_purchase_discount,promotion_1,promotion_2,promotion_3,promotion_4,promotion_5,promotion_6,revenue
0,5524,2020-12,58,75579400.0,미혼,0,58,825500,114400,709800,223600,114400,114400,8,4,3,0,0,0,0,0,1,11
1,2174,2022-06,61,60247200.0,미혼,2,38,14300,1300,7800,2600,1300,7800,1,2,2,0,0,0,0,0,0,11
2,4141,2021-11,50,93096900.0,배우자 있음,0,26,553800,63700,165100,144300,27300,54600,8,10,1,0,0,0,0,0,0,11
3,6182,2022-05,31,34639800.0,배우자 있음,1,26,14300,5200,26000,13000,3900,6500,2,4,2,0,0,0,0,0,0,11
4,5324,2022-04,34,75780900.0,배우자 있음,1,94,224900,55900,153400,59800,35100,19500,5,6,5,0,0,0,0,0,0,11

In [14]:
#구매 금액 합계 및 구매 횟수 합계 계산하기
data_amount_total = (customer_df['amount_alcohol'] + customer_df['amount_fruit'] + customer_df['amount_meat'] + customer_df['amount_fish']
                     + customer_df['amount_snack'] + customer_df['amount_general'])

In [15]:
index_amount_general = customer_df.columns.get_loc('amount_general') #amount_general 컬럼의 인덱스 구하기

In [16]:
customer_df.insert(loc = index_amount_general + 1, column = 'amount_total', value = data_amount_total) #원하는 위치에 컬럼을 삽입하기
customer_df.head()

,ID,signup_ym,age,annual_income,marital_status,children,recency,amount_alcohol,amount_fruit,amount_meat,amount_fish,amount_snack,amount_general,amount_total,num_purchase_web,num_purchase_store,num_purchase_discount,promotion_1,promotion_2,promotion_3,promotion_4,promotion_5,promotion_6,revenue
0,5524,2020-12,58,75579400.0,미혼,0,58,825500,114400,709800,223600,114400,114400,2102100,8,4,3,0,0,0,0,0,1,11
1,2174,2022-06,61,60247200.0,미혼,2,38,14300,1300,7800,2600,1300,7800,35100,1,2,2,0,0,0,0,0,0,11
2,4141,2021-11,50,93096900.0,배우자 있음,0,26,553800,63700,165100,144300,27300,54600,1008800,8,10,1,0,0,0,0,0,0,11
3,6182,2022-05,31,34639800.0,배우자 있음,1,26,14300,5200,26000,13000,3900,6500,68900,2,4,2,0,0,0,0,0,0,11
4,5324,2022-04,34,75780900.0,배우자 있음,1,94,224900,55900,153400,59800,35100,19500,548600,5,6,5,0,0,0,0,0,0,11

In [17]:
num_purchase_total = (customer_df['num_purchase_web'] + customer_df['num_purchase_store'] + customer_df['num_purchase_discount']) #같은 방식으로 총 구매 횟수 계산하기
index_num_purchase_discount = customer_df.columns.get_loc('num_purchase_discount')

customer_df.insert(loc = index_num_purchase_discount, column = 'num_purchase_total', value = num_purchase_total)

customer_df.head()

,ID,signup_ym,age,annual_income,marital_status,children,recency,amount_alcohol,amount_fruit,amount_meat,amount_fish,amount_snack,amount_general,amount_total,num_purchase_web,num_purchase_store,num_purchase_total,num_purchase_discount,promotion_1,promotion_2,promotion_3,promotion_4,promotion_5,promotion_6,revenue
0,5524,2020-12,58,75579400.0,미혼,0,58,825500,114400,709800,223600,114400,114400,2102100,8,4,15,3,0,0,0,0,0,1,11
1,2174,2022-06,61,60247200.0,미혼,2,38,14300,1300,7800,2600,1300,7800,35100,1,2,5,2,0,0,0,0,0,0,11
2,4141,2021-11,50,93096900.0,배우자 있음,0,26,553800,63700,165100,144300,27300,54600,1008800,8,10,19,1,0,0,0,0,0,0,11
3,6182,2022-05,31,34639800.0,배우자 있음,1,26,14300,5200,26000,13000,3900,6500,68900,2,4,8,2,0,0,0,0,0,0,11
4,5324,2022-04,34,75780900.0,배우자 있음,1,94,224900,55900,153400,59800,35100,19500,548600,5,6,16,5,0,0,0,0,0,0,11

In [18]:
#불필요한 컬럼 제거하기
customer_df['revenue'].describe() #11이라는 값만 존재

count    2216.0
mean       11.0
std         0.0
min        11.0
25%        11.0
50%        11.0
75%        11.0
max        11.0
Name: revenue, dtype: float64

In [19]:
customer_df = customer_df.drop(columns = ['ID', 'revenue'])
customer_df.head()

,signup_ym,age,annual_income,marital_status,children,recency,amount_alcohol,amount_fruit,amount_meat,amount_fish,amount_snack,amount_general,amount_total,num_purchase_web,num_purchase_store,num_purchase_total,num_purchase_discount,promotion_1,promotion_2,promotion_3,promotion_4,promotion_5,promotion_6
0,2020-12,58,75579400.0,미혼,0,58,825500,114400,709800,223600,114400,114400,2102100,8,4,15,3,0,0,0,0,0,1
1,2022-06,61,60247200.0,미혼,2,38,14300,1300,7800,2600,1300,7800,35100,1,2,5,2,0,0,0,0,0,0
2,2021-11,50,93096900.0,배우자 있음,0,26,553800,63700,165100,144300,27300,54600,1008800,8,10,19,1,0,0,0,0,0,0
3,2022-05,31,34639800.0,배우자 있음,1,26,14300,5200,26000,13000,3900,6500,68900,2,4,8,2,0,0,0,0,0,0
4,2022-04,34,75780900.0,배우자 있음,1,94,224900,55900,153400,59800,35100,19500,548600,5,6,16,5,0,0,0,0,0,0

In [39]:
customer_df.to_excel('전처리된파일.xlsx', index = False)